finish_knowledge_hub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_view.register, name="register"),
    path("profile/", user_view.profile, name="profile"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="registration/logged_out.html"
        ),
        name="logout",
    ),
    path("", include("knowhub.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

knowhub/urls.py
from django.urls import path

from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    CategoryDetailView,
    CategoryListView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
    ServicesListView,
    ServicesCreateView,
    ServicesDetailView,
    ServicesUpdateView,
    ServicesDeleteView,
    SearchView,
    AllCommentsView,
)
from knowhub import views

urlpatterns = [
    path("", ArticleListView.as_view(), name="knowhub-home"),
    path("about/", views.about, name="knowhub-about"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article-detail"),
    path("article/new/", ArticleCreateView.as_view(), name="article-create"),
    path(
        "article/<int:pk>/update/", ArticleUpdateView.as_view(), name="article-update"
    ),
    path(
        "article/<int:pk>/delete/", ArticleDeleteView.as_view(), name="article-delete"
    ),
    path(
        "article/<int:pk>/comment/", CommentCreateView.as_view(), name="comment-create"
    ),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
    path(
        "categories/<slug:category_slug>/",
        CategoryDetailView.as_view(),
        name="category-detail-slug",
    ),
    path("post/<int:pk>/comments/", AllCommentsView.as_view(), name="all-comments"),
    path("comment/<int:pk>/update/", CommentUpdateView.as_view(), name="comment-update"),
    path("comment/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
    path("services/", ServicesListView.as_view(), name="services-list"),
    path("services/create/", ServicesCreateView.as_view(), name="services-create"),
    path("services/<int:pk>/", ServicesDetailView.as_view(), name="services-detail"),
    path(
        "services/<int:pk>/update/",
        ServicesUpdateView.as_view(),
        name="services-update",
    ),
    path(
        "services/<int:pk>/delete/",
        ServicesDeleteView.as_view(),
        name="services-delete",
    ),
    path("search/", SearchView.as_view(), name="search-results"),
]

knowhub/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models, migrations
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify


class User(AbstractUser):
    class Meta:
        ordering = ("username",)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="category name")
    slug = models.SlugField(max_length=100, unique=True)
    description = models.CharField(max_length=255)
    creation = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("creation",)

    def save(self, *args, **kwargs):
        if not self.slug:

            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class Articles(models.Model):
    name = models.CharField(max_length=65)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="articles"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="articles",
    )
    description = models.CharField(max_length=255)
    text = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.category}: ({self.name}{self.description})"

    def get_absolute_url(self):
        return reverse("article-detail", kwargs={"pk": self.pk})


class Services(models.Model):
    name = models.CharField(max_length=65)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=5, decimal_places=2, blank=True)
    content = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="services",
    )

    def __str__(self):
        return (
            f"{self.name}: ({self.description}{self.category}{self.price}{self.owner})"
        )


class Comment(models.Model):
    text = models.TextField(max_length=300)
    date = models.DateTimeField(default=timezone.now)
    article = models.ForeignKey(
        Articles, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="comments",
    )

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.text

knowhub/forms.py
from django import forms
from django.forms import ModelForm

from knowhub.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(attrs={"class": "form-control mb-4", "rows": 3}),
        }


class ArticlesSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class ServiceSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )

knowhub/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from django.views.generic.edit import FormMixin
from knowhub.forms import CommentForm, ArticlesSearchForm, ServiceSearchForm
from django.contrib import messages
from knowhub.models import Articles, Category, Comment, Services
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)


class UserOwnedMixin:
    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.user or self.request.user == obj.owner


@login_required
def home(request):
    return render(request, "knowhub/home.html")


class ArticleListView(LoginRequiredMixin, ListView):
    model = Articles
    template_name = "knowhub/home.html"
    context_object_name = "articles"
    ordering = ["-creation_date"]


class ArticleDetailView(LoginRequiredMixin, DetailView, FormMixin):
    model = Articles
    template_name = "knowhub/articles_detail.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Articles
    fields = ["name", "description", "category", "text"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        category = form.cleaned_data["category"]
        article = form.save(commit=False)
        article.category = category
        article.save()
        self.object = article
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("article-detail", kwargs={"pk": self.object.pk})


class ArticleUpdateView(LoginRequiredMixin, UserOwnedMixin, UpdateView):
    model = Articles
    fields = ["category", "description", "name", "text"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ArticleDeleteView(LoginRequiredMixin, UserOwnedMixin, DeleteView):
    model = Articles
    success_url = "/"


class CategoryListView(LoginRequiredMixin, generic.ListView):
    model = Category
    context_object_name = "category_list"
    template_name = "knowhub/category_list.html"


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    template_name = "knowhub/category_detail.html"
    slug_url_kwarg = "category_slug"
    slug_field = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()
        articles = Articles.objects.filter(category=category)
        if self.request.GET.get("title"):
            articles = articles.filter(name__icontains=self.request.GET.get("title"))
        paginator = Paginator(articles, 6)

        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context["article_list"] = page_obj
        title = self.request.GET.get("title", "")
        context["search_form"] = ArticlesSearchForm(initial={"title": title})
        return context


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ("text",)
    template_name = "knowhub/comment.html"

    def get_success_url(self):
        return reverse("all-comments", kwargs={"pk": self.kwargs["pk"]})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.article = get_object_or_404(Articles, pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pk"] = self.kwargs["pk"]
        return context


class CommentDetailView(LoginRequiredMixin, DetailView):
    model = Comment
    template_name = "knowhub/comment_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment"] = self.object
        context["author"] = self.object.author
        return context


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ["text"]
    template_name = "knowhub/comment_update.html"

    def get_success_url(self):
        return reverse_lazy("all-comments", kwargs={"pk": self.object.article.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = "knowhub/comment_confirm_delete.html"

    def get_success_url(self):
        return reverse_lazy("all-comments", kwargs={"pk": self.object.article.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment"] = self.object
        return context


class ServicesListView(LoginRequiredMixin, ListView):
    model = Services
    context_object_name = "services_list"
    template_name = "knowhub/services_list.html"
    paginate_by = 5

    def get_queryset(self):
        form = ServiceSearchForm(self.request.GET)
        if form.is_valid():
            return Services.objects.filter(name__icontains=form.cleaned_data["title"])

        return Services.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ServicesListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = ServiceSearchForm(initial={"title": title})
        return context


class ServicesDetailView(LoginRequiredMixin, DetailView):
    model = Services
    template_name = "knowhub/services_detail.html"


class ServicesCreateView(LoginRequiredMixin, CreateView):
    model = Services
    template_name = "knowhub/services_create.html"
    fields = ["name", "description", "price", "content"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("services-detail", kwargs={"pk": self.object.pk})


class ServicesUpdateView(LoginRequiredMixin, UserOwnedMixin, UpdateView):
    model = Services
    fields = ["category", "description", "name"]
    template_name = "knowhub/services_update.html"
    success_url = reverse_lazy("services-list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ServicesDeleteView(LoginRequiredMixin, UserOwnedMixin, DeleteView):
    model = Services
    success_url = reverse_lazy("services-list")


class SearchView(View):
    def get(self, request):
        search_type = request.GET.get("search_type")
        search_query = request.GET.get("query")

        if search_query:
            articles = Articles.objects.filter(name__icontains=search_query)
            services = Services.objects.filter(name__icontains=search_query)

            if search_type == "articles":
                results = articles
            elif search_type == "services":
                results = services
            else:
                results = list(articles) + list(services)
        else:
            articles = Articles.objects.all()
            services = Services.objects.all()
            results = list(articles) + list(services)

        context = {
            "results": results,
            "search_query": search_query,
            "search_type": search_type,
        }
        return render(request, "knowhub/search_results.html", context)


class AllCommentsView(LoginRequiredMixin, ListView):
    template_name = "knowhub/all_comments.html"
    context_object_name = "comments"

    def get_queryset(self):
        article_id = self.kwargs.get("pk")
        return Comment.objects.filter(article_id=article_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = get_object_or_404(Articles, pk=self.kwargs.get("pk"))
        context["article"] = article
        context["form"] = CommentForm()
        return context


def about(request):
    return render(
        request,
        "includes/about.html",
        {"title": "About something", "is_about_page": True},
    )

templates/knowhub/all_comments.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'knowhub/comments.css' %}">
  </head>
  <body>

  <section class="comments-wrapper">

    <h3 class="comments-title">All comments</h3>
    <ul class="comments-list">
      {% for comment in comments %}
        <li class="comments-item">
          <img class="comments-item-photo" src="{{ comment.author.profile.image.url }}"
               alt="user-photo">
          <h4 class="comments-item-author">{{ comment.author.username }}</h4>
          <div class="wr">
            <p class="comments-item-text">{{ comment.text }}</p>
          </div>
          <p class="comments-item-date">{{ comment.date }}</p>
            {% if comment.author == request.user %}
      <div class="btn-wrapper">
        <a href="{% url 'comment-update' comment.pk %}">
          <button class="edit-btn">Edit</button>
        </a>
        <form action="{% url 'comment-delete' comment.pk %}" method="post">
          {% csrf_token %}
          <button class="del-btn" type="submit">Delete</button>
        </form>
      </div>
    {% endif %}
        </li>
{#        <div class="btn-wrapper">#}
{#          <a href="{% url 'comment-update' comment.pk %}">#}
{#            <button class="edit-btn">Edit</button>#}
{#          </a>#}
{#          <a href="{% url 'comment-delete' comment.pk %}">#}
{#            <button class="del-btn">Delete</button>#}
{#          </a>#}
{#        </div>#}
      {% empty %}
        <p>No comments yet.</p>
      {% endfor %}
    </ul>
    <form class="comments-form" method="post" action="{% url 'comment-create' pk=article.pk %}">
      {% csrf_token %}
      <button class="comments-btn">Send</button>
      <div class="form-group" id="comment-form">
        <label for="id_text" class="comments-label">Your review:</label><br>
        {{ form.text }}
      </div>
    </form>
  </section>

  </body>
  </html>
{% endblock content %}

templates/knowhub/articles_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Article</legend>
        <h2>Are you sure you want to delete the post "{{ object.name }}"</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{% url "article-detail" object.id %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/knowhub/articles_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static "knowhub/create_article_form.css" %}">
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Article</legend>
        {{ form.as_p }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Create or Update</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/knowhub/category_detail.html
{% extends "base.html" %}


{% load crispy_forms_filters %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" href="{% static "knowhub/main.css" %}">
{% block content %}
  <link rel="stylesheet" href="{% static "knowhub/category_detail.css" %}">
  <div class="category-page page__content">

    <a href="{% url 'article-create' %}" class="posts__btn">
      <button>Create Article</button>
    </a>


    <div class="category-info">
      <form method="get" action="" class="form">
        <input type="text" name="title" placeholder="Search by Title" class="form-control"
               value="{{ request.GET.title }}">
        <button class="btn btn-secondary" type="submit">🔎</button>
      </form>

    </div>

    <div class="posts-container">
      {% for article in article_list %}
        <div class="post">
          <div class="post-content">
            <h2 class="post-title">{{ article.title }}</h2>
            <p>{{ article.name }}</p>
            <a href="{% url "article-detail" article.id %}" class="post-link">Read more</a>
            <p class="post-date">{{ article.creation_date|date:"F d, Y" }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
    <!-- search form-->
    <div class="col-md-8">
      <!-- end block search form-->
      <!-- pagination-->
      <section class="pagination">
        <div class="pagination__container container">
          <ul class="pagination">
            {% if article_list.has_previous %}
              <li class="page-item"><a class="page-link" href="?page=1">&laquo; First Page</a></li>
              <li class="page-item"><a class="page-link"
                                       href="?page={{ article_list.previous_page_number }}">Previous</a>
              </li>
            {% endif %}
            <li class="page-item"><span
                class="page-link">Page {{ article_list.number }} of {{ article_list.paginator.num_pages }}</span></li>
            {% if article_list.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ article_list.next_page_number }}">Next</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ article_list.paginator.num_pages }}">Last
                &raquo;</a></li>
            {% endif %}
          </ul>
        </div>
      </section>
    </div>
  </div>
  <!-- end block pagination -->
{% endblock content %}

templates/knowhub/category_list.html
{% extends "base.html" %}

{% block content %}
  {% if category_list %}
    <div class="list-group">
      {% for category in category_list %}
        <a href="{% url 'category-detail' category.id %}" class="list-group-item list-group-item-action">
          <h5 class="mb-1">{{ category.name }}</h5>
          <br>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <p>There are no categories.</p>
  {% endif %}
{% endblock %}

templates/knowhub/comment.html
<form method="post" action="{% url "comment-create" pk=object.pk %}">

  {% csrf_token %}
  {{ comment_form.as_p }}
  <input type="hidden" name="articles_id" value="{{ object.pk }}">
  <button type="submit">Submit</button>
</form>

templates/knowhub/comment_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete this comment?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'article-detail' comment.article.pk %}">Cancel</a>
  </form>
{% endblock content %}

templates/knowhub/comment_detail.html
{% extends "base.html" %}

{% block content %}
  <p>{{ comment.text }}</p>
  <p>Author: {{ comment.author }}</p>
  <p>Date: {{ comment.date }}</p>

  {% if request.user == comment.author %}
    <a href="{% url 'comment-update' comment.pk %}">Update comment</a>
    <form action="{% url 'comment-delete' comment.pk %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button type="submit">Delete comment</button>
    </form>
  {% endif %}
{% endblock content %}

templates/knowhub/comment_update.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Edit Service</h5>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save Changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/knowhub/home.html
{% extends "base.html" %}


{% block carousel %}
    {% include "includes/carousel.html" %}
{% endblock carousel %}

templates/knowhub/services_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Service</legend>
        <h2>Are you sure you want to delete the service "{{ object.name }}"</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{% url "services-detail" object.id %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/knowhub/services_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static "knowhub/create_service.css" %}">
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Services</legend>
        {{ form }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Create Services</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/knowhub/services_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <link rel="stylesheet" href="{% static "knowhub/services_detail.css" %}">
  <section class="article-wrapper">
    <img class="user-photo"
         src="{{ object.owner.profile.image.url }}"
         alt="user photo">
    <p class="publ-user">{{ object.owner.username }}</p>

    {% if object.owner == request.user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1 custom-btn" href="{% url 'services-update' object.id %}">Update
          Service</a>
        <a class="btn btn-danger btn-sm mt-1 mb-1 custom-delete-btn" href="{% url 'services-delete' object.id %}">Delete
          Service</a>
      </div>
    {% endif %}
    <h2 class="article-title">{{ object.description }}</h2>
    <p class="article-text">Price: €{{ object.price }}</p>
  </section>
{% endblock content %}

templates/knowhub/services_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="content-form">
  <link rel="stylesheet" href="{% static "knowhub/service_update.css" %}">
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="button-change">Save changes</button>
</form>
  </div>
{% endblock content %}